---
- hosts: localhost
  connection: local
  tasks:
    - name: Running updates
      become: yes
      dnf:
        name: "*"
        update_only: yes
        state: latest

    - name: Remove unnecessary software
      become: yes
      package:
        name: evolution
        state: absent

    - name: Install essentials
      become: yes
      package:
        name: 
          - thunderbird
          - libreoffice
          - flatpak
        state: present
    
    - name: Adding the Flatpak Flathub repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpaks (Spotify & Slack)
      flatpak:
        name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
        state: present

    - name: Install Slack
      flatpak:
        name: https://flathub.org/repo/appstream/com.slack.Slack.flatpakref
        state: present

    - name: Install Visual Studio Code
      import_role: 
        name: vscode
      vars:
        users:
          - username: garrett
            visual_studio_code_extensions:
              - dracula-theme.theme-dracula
              - vscoss.vscode-ansible
              - tht13.html-preview-vscode
              - davidanson.vscode-markdownlint
              - ms-python.python
              - tyriar.shell-launcher
              - vscodevim.vim
            visual_code_studio_settings: {
              "git.autofetch": true,
              "window.titleBarStyle": "custom",
              "workbench.colorTheme": "Dracula"
            }
    
    - name: Installing AppImage packages (StandardNotes & Caprine)
      script: scripts/appimage.sh
  
    - name: Installing Gnome tweaks & themes
      become: yes
      package:
        name: 
          - gnome-tweaks
          - arc-theme
          - paper-icon-theme
        state: present

# Further tweaking via https://opensource.com/article/18/5/manage-your-workstation-ansible-part-3