---
- hosts: localhost
  connection: local
  tasks:
    - name: Running updates
      become: yes
      dnf:
        name: "*"
        update_only: yes
        state: latest

    - name: Remove Evolution
      become: yes
      package:
        name: evolution
        state: absent

    - name: Install Thunderbird
      become: yes
      package:
        name: thunderbird
        state: present

    - name: Install Flatpak
      become: yes
      package:
        name: flatpak
        state: present

    - name: Add the flathub flatpak repository remote
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Spotify
      flatpak:
        name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
        state: present

    - name: Install Slack
      flatpak:
        name: https://flathub.org/repo/appstream/com.slack.Slack.flatpakref
        state: present

    #- name: Install Visual Studio Code
      #become: yes
      #dnf:
        #name: https://go.microsoft.com/fwlink/?LinkID=760867
        #state: present

    - name: Install Visual Studio Code
      import_role: 
        name: vscode
      vars:
        users:
          - username: garrett
            visual_studio_code_extensions:
              - dracula-theme.theme-dracula
              - vscoss.vscode-ansible
              - tht13.html-preview-vscode
              - davidanson.vscode-markdownlint
              - ms-python.python
              - tyriar.shell-launcher
              - vscodevim.vim
            visual_code_studio_settings: {
              "git.autofetch": true,
              "window.titleBarStyle": "custom",
              "workbench.colorTheme": "Dracula"
            }