---
- hosts: localhost
  connection: local

  vars_files:
    - vars/config.yml

  tasks:
    - name: Running updates
      become: yes
      dnf:
        name: "*"
        update_only: yes
        state: latest

    - name: Remove unnecessary software
      become: yes
      package:
        name: evolution
        state: absent

    - name: Install essentials
      become: yes
      package:
        name: 
          - python2-libselinux
          - firefox
          - thunderbird
          - libreoffice
          - flatpak
        state: present
    
    - name: Enabling Google Chrome repository
      become: yes
      copy: src=google-chrome.repo
            dest=/etc/yum.repos.d/
            owner=root group=root mode=0644
      
    - name: Installing Google Chrome
      become: yes
      dnf:
        name: google-chrome-stable
        state: present
    
    - name: Adding the Flatpak Flathub repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Spotify
      flatpak:
        name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
        state: present

    - name: Install Slack
      flatpak:
        name: https://flathub.org/repo/appstream/com.slack.Slack.flatpakref
        state: present

    - name: Install Visual Studio Code
      import_role: 
        name: vscode
      vars:
        users:
          - username: "{{ username }}"
            visual_studio_code_extensions:
              - dracula-theme.theme-dracula
              - vscoss.vscode-ansible
              - tht13.html-preview-vscode
              - davidanson.vscode-markdownlint
              - ms-python.python
              - tyriar.shell-launcher
              - vscodevim.vim
            visual_code_studio_settings: {
              "git.autofetch": true,
              "window.titleBarStyle": "custom",
              "workbench.colorTheme": "Dracula"
            }
    
    - name: Installing AppImage packages (StandardNotes, PolarBookshelf & Caprine)
      script: scripts/appimage.sh
  
    - name: Installing GNOME tweaks & themes
      become: yes
      package:
        name: 
          - gnome-tweaks
          - arc-theme
          - paper-icon-theme
        state: present

# Further tweaking via https://opensource.com/article/18/5/manage-your-workstation-ansible-part-3
# Further todo: copy wallpaper based on var and set that as lockscreen/wallpaper
    - name: Setting GTK theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Arc-Dark'"
        state: present

    - name: Setting GNOME shell theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/shell/extensions/user-theme/name"
        value: "'Arc-Dark'"
        state: present

    - name: Setting icon theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/interface/icon-theme"
        value: "'Paper'"
        state: present

    - name: Setting cursor theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/interface/cursor-theme"
        value: "'Paper'"
        state: present

    - name: Setting icons in GNOME dock
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['google-chrome.desktop', 'firefox.desktop', 'com.spotify.Client.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
        state: present
      
    - name: Configuring GNOME extensions
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/shell/enabled-extensions"
        value: "['background-logo@fedorahosted.org', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'alternate-tab@gnome-shell-extensions.gcampax.github.com']"
        state: present

    - name: Making Caps Lock an additional CTRL
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/input-sources/xbk-options"
        value: "['caps:ctrl_modifier']"
        state: present