---
- hosts: localhost
  connection: local

  vars_files:
    - vars/config.yml

  tasks:
    - name: Running updates
      become: yes
      dnf:
        name: "*"
        update_only: yes
        state: latest

    - name: Remove unnecessary software
      become: yes
      package:
        name: evolution
        state: absent

    - name: Install essentials
      become: yes
      package:
        name: 
          - python2-libselinux
          #- python3-libselinux
          - python2-psutil
          #- python3-psutil
          - firefox
          - thunderbird
          - libreoffice
          - flatpak
          - leafpad
          - autokey-gtk
        state: present
    
    - name: Enabling Google Chrome repository
      become: yes
      copy: 
        src: google-chrome.repo
        dest: /etc/yum.repos.d/
        owner: root 
        group: root 
        mode: 0644
      
    - name: Installing Google Chrome
      become: yes
      dnf:
        name: google-chrome-stable
        state: present
    
    - name: Adding the Flatpak Flathub repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Spotify
      become: yes
      flatpak:
        name: https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
        state: present

    - name: Install Slack
      become: yes
      flatpak:
        name: https://flathub.org/repo/appstream/com.slack.Slack.flatpakref
        state: present

    - name: Install Visual Studio Code
      import_role: 
        name: vscode
      vars:
        users:
          - username: "{{ username }}"
            visual_studio_code_extensions:
              - dracula-theme.theme-dracula
              - vscoss.vscode-ansible
              - tht13.html-preview-vscode
              - davidanson.vscode-markdownlint
              - ms-python.python
              - tyriar.shell-launcher
              - vscodevim.vim
            visual_studio_code_settings: {
              "git.autofetch": true,
              "window.titleBarStyle": "custom",
              "workbench.colorTheme": "Dracula"
            }
    
    - name: Installing AppImage packages (StandardNotes, PolarBookshelf & Caprine)
      script: scripts/appimage.sh
  
    - name: Installing GNOME tweaks & themes
      become: yes
      package:
        name: 
          - gnome-tweaks
          - arc-theme
          - paper-icon-theme
        state: present

    - name: Copying wallpaper to Pictures folder
      copy:
        src: "wallpapers/{{ wallpaper }}"
        dest: "/home/{{ username }}/Pictures/Wallpapers/"
        owner: "{{ username }}"
        mode: 0600

    - name: Setting GNOME wallpaper
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///home/{{ username }}/Pictures/Wallpapers/{{ wallpaper }}'"

    - name: Setting GDM lockscreen
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/screensaver/picture-uri"
        value: "'file:///home/{{ username }}/Pictures/Wallpapers/{{ wallpaper }}'"

    - name: Setting GTK theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Arc-Dark'"

    - name: Setting GNOME shell theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/shell/extensions/user-theme/name"
        value: "'Arc-Dark'"

    - name: Setting icon theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/interface/icon-theme"
        value: "'Paper'"

    - name: Setting cursor theme
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/interface/cursor-theme"
        value: "'Paper'"

    - name: Setting icons in GNOME dock
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['google-chrome.desktop', 'firefox.desktop', 'com.slack.Slack.desktop', 'com.spotify.Client.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
      
    - name: Configuring GNOME extensions
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/shell/enabled-extensions"
        value: "['background-logo@fedorahosted.org', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'alternate-tab@gnome-shell-extensions.gcampax.github.com']"

    - name: Setting Window titlebar settings
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"
    - name: Making Caps Lock an additional CTRL
      become: "{{ username }}"
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:ctrl_modifier']"
